#clock
set_property PACKAGE_PIN W5 [get_ports i_clock]
	set_property IOSTANDARD LVCMOS33 [get_ports i_clock]
	create_clock -add -name sys_clk_pin -period 20.00 -waveform {0 10} [get_ports i_clock]

#switches
set_property PACKAGE_PIN V17 [get_ports {i_switches[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {i_switches[0]}]
set_property PACKAGE_PIN V16 [get_ports {i_switches[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {i_switches[1]}]
set_property PACKAGE_PIN W16 [get_ports {i_switches[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {i_switches[2]}]
set_property PACKAGE_PIN W17 [get_ports {i_switches[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {i_switches[3]}]
set_property PACKAGE_PIN W15 [get_ports {i_switches[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {i_switches[4]}]
set_property PACKAGE_PIN V15 [get_ports {i_switches[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {i_switches[5]}]
set_property PACKAGE_PIN W14 [get_ports {i_switches[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {i_switches[6]}]
set_property PACKAGE_PIN W13 [get_ports {i_switches[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {i_switches[7]}]
    
# leds
set_property PACKAGE_PIN U16 [get_ports {o_resultado[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {o_resultado[0]}]
set_property PACKAGE_PIN E19 [get_ports {o_resultado[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {o_resultado[1]}]
set_property PACKAGE_PIN U19 [get_ports {o_resultado[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {o_resultado[2]}]
set_property PACKAGE_PIN V19 [get_ports {o_resultado[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {o_resultado[3]}]
set_property PACKAGE_PIN W18 [get_ports {o_resultado[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {o_resultado[4]}]
set_property PACKAGE_PIN U15 [get_ports {o_resultado[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {o_resultado[5]}]
set_property PACKAGE_PIN U14 [get_ports {o_resultado[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {o_resultado[6]}]
set_property PACKAGE_PIN V14 [get_ports {o_resultado[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {o_resultado[7]}]
    
#botones
set_property PACKAGE_PIN W19 [get_ports {i_buttons[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {i_buttons[0]}]
set_property PACKAGE_PIN U18 [get_ports {i_buttons[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {i_buttons[1]}]
set_property PACKAGE_PIN T17 [get_ports {i_buttons[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {i_buttons[2]}]
set_property PACKAGE_PIN T18 [get_ports i_reset]
    set_property IOSTANDARD LVCMOS33 [get_ports i_reset]